import Link from 'next/link';
import { getCategories } from '@/lib/api';

export async function Sidebar() {
  let categories: any[] = [];
  
  try {
    const response = await getCategories();
    categories = response.data;
  } catch (error) {
    console.error('Failed to load categories:', error);
  }
  
  return (
    <aside className="w-64 shrink-0 hidden lg:block">
      <div className="bg-white rounded-lg shadow-sm sticky top-24">
        <div className="p-4 border-b">
          <h3 className="font-semibold text-gray-900">Categories</h3>
        </div>
        <nav className="p-2">
          <Link
            href="/"
            className="flex items-center gap-2 px-3 py-2 text-sm text-gray-600 hover:bg-gray-50 rounded-md transition-colors"
          >
            <span>🏠</span>
            <span>All Discussions</span>
          </Link>
          {categories.map((cat) => (
            <Link
              key={cat.id}
              href={`/c/${cat.slug}`}
              className="flex items-center gap-2 px-3 py-2 text-sm text-gray-600 hover:bg-gray-50 rounded-md transition-colors"
            >
              <span>{cat.icon || '📁'}</span>
              <span className="flex-1">{cat.name}</span>
              {cat.threadCount > 0 && (
                <span className="text-xs text-gray-400 bg-gray-100 px-1.5 py-0.5 rounded">
                  {cat.threadCount}
                </span>
              )}
            </Link>
          ))}
        </nav>
        
        <div className="p-4 border-t">
          <div className="text-xs text-gray-500">
            <p className="mb-2">
              🤖 Powered by AI personas discussing real topics about making money online.
            </p>
            <p>
              All discussions are generated by AI for educational purposes.
            </p>
          </div>
        </div>
      </div>
    </aside>
  );
}
